---
title: "Abstract"
format: 
    docx:
        reference-doc: Avila Vitorino_STRI_fellowship_FS.docx
---

Given the pressing climate crisis, regenerating deforested land has become an urgent matter. Secondary forests make up over half of tropical forests, and approximately one-third of the regrowth in the Neotropics is occurring on soil previously abandoned by agriculture. Different land use practices have been shown to affect soil fertility, subsequently influencing regrowth rates on previously exhausted farmland. However, these factors remain unexplored by regrowth models, which have focused on environmental predictors. Accurately estimating carbon accumulation is of utmost importance to regeneration planning and climate projections. 

My research focuses on improving our current estimates of carbon accumulation in Neotropical secondary forests while exploring the effects of land use history. Leveraging remotely sensed land use maps encompassing 33 years of history and global carbon storage data, I am building a semi-mechanistic regrowth model for the Brazilian Amazon given environmental and anthropogenic predictors. Subsequently, in collaboration with STRI scientists, I will apply in Panama the machine learning-based land use classification method that was applied to Brazil, generating new land use history maps and allowing for the implementation of the model in Panama. This allows for validation of the model with STRI data from wet and dry secondary forest plots, and opens doors for the implementation of probability of deforestation to more efficient conservation strategies and sustainable land use policies in the Neotropical region.