---
title: "Diversity Statement"
format: 
    docx:
        reference-doc: Avila Vitorino_STRI_fellowship_FS.docx

---

Portuguese is the most similar language to Spanish, and Brazilians are blessed with an advantageous starting point for bilingualism. Disappointingly, most of my fellow countrypeople resign themselves to speaking "portuñol" in interactions with our hispanic neighbors, as mimics and forced accents can usually get the idea across well enough. I have always defended that the Brazilian unwillingness to learn proper Spanish is the reason for our isolation in our own region. Any Latino can tell you that Brazil is like an estranged cousin that shows up for Christmases, but is not an active participant of the family WhatsApp group. This distance can stifle promising opportunities; however, an unlikely encounter with Colombian cumbia ignited my curiosity. Subsequent dives into hispanic art and culture fascinated me with the many ways in which it intersects and diverges from my own, and with how much of what I love about my country is shared by its neighbors. I diligently studied Spanish, hoping to reunite with the rest of the cousins and expand the borders of home to Mexico and Patagonia. Bolívar could have found no more passionate follower.

As I grew up, I realized that as a community, besides sharing a taste for vibrant music and rice with beans, we also face similar challenges: deforestation, foreign exploitation of our natural resources, violation of indigenous rights, and death threats to those that dare to fight it. Still, we work in parallel, grappling with insufficient funding for each nation's own research programs, making the exchange of hard-earned resources an elusive goal. Hardship isolates us further, and once again, this isolation stifles our potential; conservation and research are much less impactful when done alone. As a scientist working on tropical forest conservation and regrowth, I am hopeful to do my part to help bridge this gap. Since high school, as a kid that had way too much interest in foreign languages, I have volunteered as my local astronomy club as a translator, which was my first step on my path to establish connections between Brazilian scientists and students with the rest of Latin America and the world. For my graduate studies, I have seeked to learn from the Panamanian experience through connections with the Smithsonian - an interesting place to begin, where Bolívar himself pointed as the future Corinth of "América Entera". I am in another advantageous starting point, this time for a career as a researcher, with connections to Canada, Panama and Brazil, and I am eager to make the most of my position to help build bridges between the scientific communities of the Americas.

